name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: ls
      run: ls Dockeriles/postgre
    - name: Checkout
      uses: actions/checkout@v2
    - name: Docker Build and Push
      uses: docker/build-push-action@v2
      with:
        context: ./Dockeriles/postgre
        file: ./Dockerfile
        tags: my-image-name:t10
        build-args: |
            "NPM_TOKEN=${{ secrets.TOKEN }}"
        push: true
    - name: Build the Docker image
      run: docker build Dockeriles/postgre --file Dockerfile --tag my-image-name:$(date +%s)
